### ISSUE TITLE
org-site.py: Error - templates-dir value 'test/src/templates' is not a directory

### ISSUE THREAD

**Issue by jbz-dev** [ConradBailey/org-site#1]
Hi,

First I want to thank you for your work on `org-site`. I'm hooked by the simplicity of it and want to try it.

So I fetched `org-site.py` and `org2html.sh` and cloned `org-site-demo`.

I launch `./org-site.py src/ docs/` and I have the following error:

```
org-site.py: Error - templates-dir value 'test/src/templates' is not a directory
```

**Comment by ConradBailey** [comment]
Hey, thanks for engaging! As far as I know you're the only person besides myself who's touched this. One artifact of that is that I expect it will be a little cludgy to outsiders, and this is the first symptom of that.

Right now `org-site.py` requires absolute paths for the arguments. In my workflow it's just something I've lived with, but I'll get around to fixing it today. Until then you can work around it with something like `$ ./org-site.py $PWD/src/ $PWD/docs/`

If you encounter any other stumbling blocks or confusion just keep opening issues!

**Comment by ConradBailey** [comment]
@Bridouz Updates should have fixed this; let me know if it worked for you.

**Comment by jbz-dev** [comment]
Works :)
